# run: conda env create --file environment.yml
# activate: source activate conservprior
name: conservprior
channels:
  - conda-forge
dependencies: 
  - python=2.7
  - basemap
  - matplotlib
  - numpy
  - pandas
  - retriever=2.*
  - seaborn
  - pip:
    - macroecotools